/*
 Navicat Premium Data Transfer

 Source Server         : MySQL
 Source Server Type    : MySQL
 Source Server Version : 50525
 Source Host           : localhost:3306
 Source Schema         : chenxue

 Target Server Type    : MySQL
 Target Server Version : 50525
 File Encoding         : 65001

 Date: 24/10/2019 19:04:26
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for city
-- ----------------------------
DROP TABLE IF EXISTS `city`;
CREATE TABLE `city`  (
  `cityId` int(11) NOT NULL AUTO_INCREMENT,
  `cityName` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `pId` int(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cityId`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 463 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of city
-- ----------------------------
INSERT INTO `city` VALUES (1, '朝阳区', 1);
INSERT INTO `city` VALUES (2, '海淀区', 1);
INSERT INTO `city` VALUES (3, '通州区', 1);
INSERT INTO `city` VALUES (4, '房山区', 1);
INSERT INTO `city` VALUES (5, '丰台区', 1);
INSERT INTO `city` VALUES (6, '昌平区', 1);
INSERT INTO `city` VALUES (7, '大兴区', 1);
INSERT INTO `city` VALUES (8, '顺义区', 1);
INSERT INTO `city` VALUES (9, '西城区', 1);
INSERT INTO `city` VALUES (10, '延庆县', 1);
INSERT INTO `city` VALUES (11, '石景山区', 1);
INSERT INTO `city` VALUES (12, '宣武区', 1);
INSERT INTO `city` VALUES (13, '怀柔区', 1);
INSERT INTO `city` VALUES (14, '崇文区', 1);
INSERT INTO `city` VALUES (15, '密云县', 1);
INSERT INTO `city` VALUES (16, '东城区', 1);
INSERT INTO `city` VALUES (17, '门头沟区', 1);
INSERT INTO `city` VALUES (18, '平谷区', 1);
INSERT INTO `city` VALUES (19, '东莞市', 2);
INSERT INTO `city` VALUES (20, '广州市', 2);
INSERT INTO `city` VALUES (21, '中山市', 2);
INSERT INTO `city` VALUES (22, '深圳市', 2);
INSERT INTO `city` VALUES (23, '惠州市', 2);
INSERT INTO `city` VALUES (24, '江门市', 2);
INSERT INTO `city` VALUES (25, '珠海市', 2);
INSERT INTO `city` VALUES (26, '汕头市', 2);
INSERT INTO `city` VALUES (27, '佛山市', 2);
INSERT INTO `city` VALUES (28, '湛江市', 2);
INSERT INTO `city` VALUES (29, '河源市', 2);
INSERT INTO `city` VALUES (30, '肇庆市', 2);
INSERT INTO `city` VALUES (31, '潮州市', 2);
INSERT INTO `city` VALUES (32, '清远市', 2);
INSERT INTO `city` VALUES (33, '韶关市', 2);
INSERT INTO `city` VALUES (34, '揭阳市', 2);
INSERT INTO `city` VALUES (35, '阳江市', 2);
INSERT INTO `city` VALUES (36, '云浮市', 2);
INSERT INTO `city` VALUES (37, '茂名市', 2);
INSERT INTO `city` VALUES (38, '梅州市', 2);
INSERT INTO `city` VALUES (39, '汕尾市', 2);
INSERT INTO `city` VALUES (40, '济南市', 3);
INSERT INTO `city` VALUES (41, '青岛市', 3);
INSERT INTO `city` VALUES (42, '临沂市', 3);
INSERT INTO `city` VALUES (43, '济宁市', 3);
INSERT INTO `city` VALUES (44, '菏泽市', 3);
INSERT INTO `city` VALUES (45, '烟台市', 3);
INSERT INTO `city` VALUES (46, '泰安市', 3);
INSERT INTO `city` VALUES (47, '淄博市', 3);
INSERT INTO `city` VALUES (48, '潍坊市', 3);
INSERT INTO `city` VALUES (49, '日照市', 3);
INSERT INTO `city` VALUES (50, '威海市', 3);
INSERT INTO `city` VALUES (51, '滨州市', 3);
INSERT INTO `city` VALUES (52, '东营市', 3);
INSERT INTO `city` VALUES (53, '聊城市', 3);
INSERT INTO `city` VALUES (54, '德州市', 3);
INSERT INTO `city` VALUES (55, '莱芜市', 3);
INSERT INTO `city` VALUES (56, '枣庄市', 3);
INSERT INTO `city` VALUES (57, '苏州市', 4);
INSERT INTO `city` VALUES (58, '徐州市', 4);
INSERT INTO `city` VALUES (59, '盐城市', 4);
INSERT INTO `city` VALUES (60, '无锡市', 4);
INSERT INTO `city` VALUES (61, '南京市', 4);
INSERT INTO `city` VALUES (62, '南通市', 4);
INSERT INTO `city` VALUES (63, '连云港市', 4);
INSERT INTO `city` VALUES (64, '常州市', 4);
INSERT INTO `city` VALUES (65, '扬州市', 4);
INSERT INTO `city` VALUES (66, '镇江市', 4);
INSERT INTO `city` VALUES (67, '淮安市', 4);
INSERT INTO `city` VALUES (68, '泰州市', 4);
INSERT INTO `city` VALUES (69, '宿迁市', 4);
INSERT INTO `city` VALUES (70, '郑州市', 5);
INSERT INTO `city` VALUES (71, '南阳市', 5);
INSERT INTO `city` VALUES (72, '新乡市', 5);
INSERT INTO `city` VALUES (73, '安阳市', 5);
INSERT INTO `city` VALUES (74, '洛阳市', 5);
INSERT INTO `city` VALUES (75, '信阳市', 5);
INSERT INTO `city` VALUES (76, '平顶山市', 5);
INSERT INTO `city` VALUES (77, '周口市', 5);
INSERT INTO `city` VALUES (78, '商丘市', 5);
INSERT INTO `city` VALUES (79, '开封市', 5);
INSERT INTO `city` VALUES (80, '焦作市', 5);
INSERT INTO `city` VALUES (81, '驻马店市', 5);
INSERT INTO `city` VALUES (82, '濮阳市', 5);
INSERT INTO `city` VALUES (83, '三门峡市', 5);
INSERT INTO `city` VALUES (84, '漯河市', 5);
INSERT INTO `city` VALUES (85, '许昌市', 5);
INSERT INTO `city` VALUES (86, '鹤壁市', 5);
INSERT INTO `city` VALUES (87, '济源市', 5);
INSERT INTO `city` VALUES (88, '松江区', 6);
INSERT INTO `city` VALUES (89, '宝山区', 6);
INSERT INTO `city` VALUES (90, '金山区', 6);
INSERT INTO `city` VALUES (91, '嘉定区', 6);
INSERT INTO `city` VALUES (92, '南汇区', 6);
INSERT INTO `city` VALUES (93, '青浦区', 6);
INSERT INTO `city` VALUES (94, '浦东新区', 6);
INSERT INTO `city` VALUES (95, '奉贤区', 6);
INSERT INTO `city` VALUES (96, '闵行区', 6);
INSERT INTO `city` VALUES (97, '徐汇区', 6);
INSERT INTO `city` VALUES (98, '静安区', 6);
INSERT INTO `city` VALUES (99, '黄浦区', 6);
INSERT INTO `city` VALUES (100, '普陀区', 6);
INSERT INTO `city` VALUES (101, '杨浦区', 6);
INSERT INTO `city` VALUES (102, '虹口区', 6);
INSERT INTO `city` VALUES (103, '闸北区', 6);
INSERT INTO `city` VALUES (104, '长宁区', 6);
INSERT INTO `city` VALUES (105, '崇明县', 6);
INSERT INTO `city` VALUES (106, '卢湾区', 6);
INSERT INTO `city` VALUES (107, '石家庄市', 7);
INSERT INTO `city` VALUES (108, '唐山市', 7);
INSERT INTO `city` VALUES (109, '保定市', 7);
INSERT INTO `city` VALUES (110, '邯郸市', 7);
INSERT INTO `city` VALUES (111, '邢台市', 7);
INSERT INTO `city` VALUES (112, '河北区', 7);
INSERT INTO `city` VALUES (113, '沧州市', 7);
INSERT INTO `city` VALUES (114, '秦皇岛市', 7);
INSERT INTO `city` VALUES (115, '张家口市', 7);
INSERT INTO `city` VALUES (116, '衡水市', 7);
INSERT INTO `city` VALUES (117, '廊坊市', 7);
INSERT INTO `city` VALUES (118, '承德市', 7);
INSERT INTO `city` VALUES (119, '温州市', 8);
INSERT INTO `city` VALUES (120, '宁波市', 8);
INSERT INTO `city` VALUES (121, '杭州市', 8);
INSERT INTO `city` VALUES (122, '台州市', 8);
INSERT INTO `city` VALUES (123, '嘉兴市', 8);
INSERT INTO `city` VALUES (124, '金华市', 8);
INSERT INTO `city` VALUES (125, '湖州市', 8);
INSERT INTO `city` VALUES (126, '绍兴市', 8);
INSERT INTO `city` VALUES (127, '舟山市', 8);
INSERT INTO `city` VALUES (128, '丽水市', 8);
INSERT INTO `city` VALUES (129, '衢州市', 8);
INSERT INTO `city` VALUES (130, '香港特别行政区', 9);
INSERT INTO `city` VALUES (131, '西安市', 10);
INSERT INTO `city` VALUES (132, '咸阳市', 10);
INSERT INTO `city` VALUES (133, '宝鸡市', 10);
INSERT INTO `city` VALUES (134, '汉中市', 10);
INSERT INTO `city` VALUES (135, '渭南市', 10);
INSERT INTO `city` VALUES (136, '安康市', 10);
INSERT INTO `city` VALUES (137, '榆林市', 10);
INSERT INTO `city` VALUES (138, '商洛市', 10);
INSERT INTO `city` VALUES (139, '延安市', 10);
INSERT INTO `city` VALUES (140, '铜川市', 10);
INSERT INTO `city` VALUES (141, '长沙市', 11);
INSERT INTO `city` VALUES (142, '邵阳市', 11);
INSERT INTO `city` VALUES (143, '常德市', 11);
INSERT INTO `city` VALUES (144, '衡阳市', 11);
INSERT INTO `city` VALUES (145, '株洲市', 11);
INSERT INTO `city` VALUES (146, '湘潭市', 11);
INSERT INTO `city` VALUES (147, '永州市', 11);
INSERT INTO `city` VALUES (148, '岳阳市', 11);
INSERT INTO `city` VALUES (149, '怀化市', 11);
INSERT INTO `city` VALUES (150, '郴州市', 11);
INSERT INTO `city` VALUES (151, '娄底市', 11);
INSERT INTO `city` VALUES (152, '益阳市', 11);
INSERT INTO `city` VALUES (153, '张家界市', 11);
INSERT INTO `city` VALUES (154, '湘西州', 11);
INSERT INTO `city` VALUES (155, '江北区', 12);
INSERT INTO `city` VALUES (156, '渝北区', 12);
INSERT INTO `city` VALUES (157, '沙坪坝区', 12);
INSERT INTO `city` VALUES (158, '九龙坡区', 12);
INSERT INTO `city` VALUES (159, '万州区', 12);
INSERT INTO `city` VALUES (160, '永川市', 12);
INSERT INTO `city` VALUES (161, '南岸区', 12);
INSERT INTO `city` VALUES (162, '酉阳县', 12);
INSERT INTO `city` VALUES (163, '北碚区', 12);
INSERT INTO `city` VALUES (164, '涪陵区', 12);
INSERT INTO `city` VALUES (165, '秀山县', 12);
INSERT INTO `city` VALUES (166, '巴南区', 12);
INSERT INTO `city` VALUES (167, '渝中区', 12);
INSERT INTO `city` VALUES (168, '石柱县', 12);
INSERT INTO `city` VALUES (169, '忠县', 12);
INSERT INTO `city` VALUES (170, '合川市', 12);
INSERT INTO `city` VALUES (171, '大渡口区', 12);
INSERT INTO `city` VALUES (172, '开县', 12);
INSERT INTO `city` VALUES (173, '长寿区', 12);
INSERT INTO `city` VALUES (174, '荣昌县', 12);
INSERT INTO `city` VALUES (175, '云阳县', 12);
INSERT INTO `city` VALUES (176, '梁平县', 12);
INSERT INTO `city` VALUES (177, '潼南县', 12);
INSERT INTO `city` VALUES (178, '江津市', 12);
INSERT INTO `city` VALUES (179, '彭水县', 12);
INSERT INTO `city` VALUES (180, '璧山县', 12);
INSERT INTO `city` VALUES (181, '綦江县', 12);
INSERT INTO `city` VALUES (182, '大足县', 12);
INSERT INTO `city` VALUES (183, '黔江区', 12);
INSERT INTO `city` VALUES (184, '巫溪县', 12);
INSERT INTO `city` VALUES (185, '巫山县', 12);
INSERT INTO `city` VALUES (186, '垫江县', 12);
INSERT INTO `city` VALUES (187, '丰都县', 12);
INSERT INTO `city` VALUES (188, '武隆县', 12);
INSERT INTO `city` VALUES (189, '万盛区', 12);
INSERT INTO `city` VALUES (190, '铜梁县', 12);
INSERT INTO `city` VALUES (191, '南川市', 12);
INSERT INTO `city` VALUES (192, '奉节县', 12);
INSERT INTO `city` VALUES (193, '双桥区', 12);
INSERT INTO `city` VALUES (194, '城口县　', 12);
INSERT INTO `city` VALUES (195, '漳州市', 13);
INSERT INTO `city` VALUES (196, '泉州市', 13);
INSERT INTO `city` VALUES (197, '厦门市', 13);
INSERT INTO `city` VALUES (198, '福州市', 13);
INSERT INTO `city` VALUES (199, '莆田市', 13);
INSERT INTO `city` VALUES (200, '宁德市', 13);
INSERT INTO `city` VALUES (201, '三明市', 13);
INSERT INTO `city` VALUES (202, '南平市', 13);
INSERT INTO `city` VALUES (203, '龙岩市', 13);
INSERT INTO `city` VALUES (204, '和平区', 14);
INSERT INTO `city` VALUES (205, '北辰区', 14);
INSERT INTO `city` VALUES (206, '河北区', 14);
INSERT INTO `city` VALUES (207, '河西区', 14);
INSERT INTO `city` VALUES (208, '西青区', 14);
INSERT INTO `city` VALUES (209, '津南区', 14);
INSERT INTO `city` VALUES (210, '东丽区', 14);
INSERT INTO `city` VALUES (211, '武清区', 14);
INSERT INTO `city` VALUES (212, '宝坻区', 14);
INSERT INTO `city` VALUES (213, '红桥区', 14);
INSERT INTO `city` VALUES (214, '大港区', 14);
INSERT INTO `city` VALUES (215, '汉沽区', 14);
INSERT INTO `city` VALUES (216, '静海县', 14);
INSERT INTO `city` VALUES (217, '宁河县', 14);
INSERT INTO `city` VALUES (218, '塘沽区', 14);
INSERT INTO `city` VALUES (219, '蓟县', 14);
INSERT INTO `city` VALUES (220, '南开区', 14);
INSERT INTO `city` VALUES (221, '河东区', 14);
INSERT INTO `city` VALUES (222, '昆明市', 15);
INSERT INTO `city` VALUES (223, '红河州', 15);
INSERT INTO `city` VALUES (224, '大理州', 15);
INSERT INTO `city` VALUES (225, '文山州', 15);
INSERT INTO `city` VALUES (226, '德宏州', 15);
INSERT INTO `city` VALUES (227, '曲靖市', 15);
INSERT INTO `city` VALUES (228, '昭通市', 15);
INSERT INTO `city` VALUES (229, '楚雄州', 15);
INSERT INTO `city` VALUES (230, '保山市', 15);
INSERT INTO `city` VALUES (231, '玉溪市', 15);
INSERT INTO `city` VALUES (232, '丽江地区', 15);
INSERT INTO `city` VALUES (233, '临沧地区', 15);
INSERT INTO `city` VALUES (234, '思茅地区', 15);
INSERT INTO `city` VALUES (235, '西双版纳州', 15);
INSERT INTO `city` VALUES (236, '怒江州', 15);
INSERT INTO `city` VALUES (237, '迪庆州　', 15);
INSERT INTO `city` VALUES (238, '成都市', 16);
INSERT INTO `city` VALUES (239, '绵阳市', 16);
INSERT INTO `city` VALUES (240, '广元市', 16);
INSERT INTO `city` VALUES (241, '达州市', 16);
INSERT INTO `city` VALUES (242, '南充市', 16);
INSERT INTO `city` VALUES (243, '德阳市', 16);
INSERT INTO `city` VALUES (244, '广安市', 16);
INSERT INTO `city` VALUES (245, '阿坝州', 16);
INSERT INTO `city` VALUES (246, '巴中市', 16);
INSERT INTO `city` VALUES (247, '遂宁市', 16);
INSERT INTO `city` VALUES (248, '内江市', 16);
INSERT INTO `city` VALUES (249, '凉山州', 16);
INSERT INTO `city` VALUES (250, '攀枝花市', 16);
INSERT INTO `city` VALUES (251, '乐山市', 16);
INSERT INTO `city` VALUES (252, '自贡市', 16);
INSERT INTO `city` VALUES (253, '泸州市', 16);
INSERT INTO `city` VALUES (254, '雅安市', 16);
INSERT INTO `city` VALUES (255, '宜宾市', 16);
INSERT INTO `city` VALUES (256, '资阳市', 16);
INSERT INTO `city` VALUES (257, '眉山市', 16);
INSERT INTO `city` VALUES (258, '甘孜州　', 16);
INSERT INTO `city` VALUES (259, '贵港市', 17);
INSERT INTO `city` VALUES (260, '玉林市', 17);
INSERT INTO `city` VALUES (261, '北海市', 17);
INSERT INTO `city` VALUES (262, '南宁市', 17);
INSERT INTO `city` VALUES (263, '柳州市', 17);
INSERT INTO `city` VALUES (264, '桂林市', 17);
INSERT INTO `city` VALUES (265, '梧州市', 17);
INSERT INTO `city` VALUES (266, '钦州市', 17);
INSERT INTO `city` VALUES (267, '来宾市', 17);
INSERT INTO `city` VALUES (268, '河池市', 17);
INSERT INTO `city` VALUES (269, '百色市', 17);
INSERT INTO `city` VALUES (270, '贺州市', 17);
INSERT INTO `city` VALUES (271, '崇左市', 17);
INSERT INTO `city` VALUES (272, '防城港市　', 17);
INSERT INTO `city` VALUES (273, '芜湖市', 18);
INSERT INTO `city` VALUES (274, '合肥市', 18);
INSERT INTO `city` VALUES (275, '六安市', 18);
INSERT INTO `city` VALUES (276, '宿州市', 18);
INSERT INTO `city` VALUES (277, '阜阳市', 18);
INSERT INTO `city` VALUES (278, '安庆市', 18);
INSERT INTO `city` VALUES (279, '马鞍山市', 18);
INSERT INTO `city` VALUES (280, '蚌埠市', 18);
INSERT INTO `city` VALUES (281, '淮北市', 18);
INSERT INTO `city` VALUES (282, '淮南市', 18);
INSERT INTO `city` VALUES (283, '宣城市', 18);
INSERT INTO `city` VALUES (284, '黄山市', 18);
INSERT INTO `city` VALUES (285, '铜陵市', 18);
INSERT INTO `city` VALUES (286, '亳州市', 18);
INSERT INTO `city` VALUES (287, '池州市', 18);
INSERT INTO `city` VALUES (288, '巢湖市', 18);
INSERT INTO `city` VALUES (289, '滁州市', 18);
INSERT INTO `city` VALUES (290, '三亚市', 19);
INSERT INTO `city` VALUES (291, '海口市', 19);
INSERT INTO `city` VALUES (292, '琼海市', 19);
INSERT INTO `city` VALUES (293, '文昌市', 19);
INSERT INTO `city` VALUES (294, '东方市', 19);
INSERT INTO `city` VALUES (295, '昌江县', 19);
INSERT INTO `city` VALUES (296, '陵水县', 19);
INSERT INTO `city` VALUES (297, '乐东县', 19);
INSERT INTO `city` VALUES (298, '五指山市', 19);
INSERT INTO `city` VALUES (299, '保亭县', 19);
INSERT INTO `city` VALUES (300, '澄迈县', 19);
INSERT INTO `city` VALUES (301, '万宁市', 19);
INSERT INTO `city` VALUES (302, '儋州市', 19);
INSERT INTO `city` VALUES (303, '临高县', 19);
INSERT INTO `city` VALUES (304, '白沙县', 19);
INSERT INTO `city` VALUES (305, '定安县', 19);
INSERT INTO `city` VALUES (306, '琼中县', 19);
INSERT INTO `city` VALUES (307, '屯昌县　', 19);
INSERT INTO `city` VALUES (308, '南昌市', 20);
INSERT INTO `city` VALUES (309, '赣州市', 20);
INSERT INTO `city` VALUES (310, '上饶市', 20);
INSERT INTO `city` VALUES (311, '吉安市', 20);
INSERT INTO `city` VALUES (312, '九江市', 20);
INSERT INTO `city` VALUES (313, '新余市', 20);
INSERT INTO `city` VALUES (314, '抚州市', 20);
INSERT INTO `city` VALUES (315, '宜春市', 20);
INSERT INTO `city` VALUES (316, '景德镇市', 20);
INSERT INTO `city` VALUES (317, '萍乡市', 20);
INSERT INTO `city` VALUES (318, '鹰潭市　', 20);
INSERT INTO `city` VALUES (319, '武汉市', 21);
INSERT INTO `city` VALUES (320, '宜昌市', 21);
INSERT INTO `city` VALUES (321, '襄樊市', 21);
INSERT INTO `city` VALUES (322, '荆州市', 21);
INSERT INTO `city` VALUES (323, '恩施州', 21);
INSERT INTO `city` VALUES (324, '孝感市', 21);
INSERT INTO `city` VALUES (325, '黄冈市', 21);
INSERT INTO `city` VALUES (326, '十堰市', 21);
INSERT INTO `city` VALUES (327, '咸宁市', 21);
INSERT INTO `city` VALUES (328, '黄石市', 21);
INSERT INTO `city` VALUES (329, '仙桃市', 21);
INSERT INTO `city` VALUES (330, '随州市', 21);
INSERT INTO `city` VALUES (331, '天门市', 21);
INSERT INTO `city` VALUES (332, '荆门市', 21);
INSERT INTO `city` VALUES (333, '潜江市', 21);
INSERT INTO `city` VALUES (334, '鄂州市', 21);
INSERT INTO `city` VALUES (335, '神农架林区　', 21);
INSERT INTO `city` VALUES (336, '太原市', 22);
INSERT INTO `city` VALUES (337, '大同市', 22);
INSERT INTO `city` VALUES (338, '运城市', 22);
INSERT INTO `city` VALUES (339, '长治市', 22);
INSERT INTO `city` VALUES (340, '晋城市', 22);
INSERT INTO `city` VALUES (341, '忻州市', 22);
INSERT INTO `city` VALUES (342, '临汾市', 22);
INSERT INTO `city` VALUES (343, '吕梁市', 22);
INSERT INTO `city` VALUES (344, '晋中市', 22);
INSERT INTO `city` VALUES (345, '阳泉市', 22);
INSERT INTO `city` VALUES (346, '朔州市　', 22);
INSERT INTO `city` VALUES (347, '大连市', 23);
INSERT INTO `city` VALUES (348, '沈阳市', 23);
INSERT INTO `city` VALUES (349, '丹东市', 23);
INSERT INTO `city` VALUES (350, '辽阳市', 23);
INSERT INTO `city` VALUES (351, '葫芦岛市', 23);
INSERT INTO `city` VALUES (352, '锦州市', 23);
INSERT INTO `city` VALUES (353, '朝阳市', 23);
INSERT INTO `city` VALUES (354, '营口市', 23);
INSERT INTO `city` VALUES (355, '鞍山市', 23);
INSERT INTO `city` VALUES (356, '抚顺市', 23);
INSERT INTO `city` VALUES (357, '阜新市', 23);
INSERT INTO `city` VALUES (358, '本溪市', 23);
INSERT INTO `city` VALUES (359, '盘锦市', 23);
INSERT INTO `city` VALUES (360, '铁岭市　', 23);
INSERT INTO `city` VALUES (361, '台北市', 24);
INSERT INTO `city` VALUES (362, '高雄市', 24);
INSERT INTO `city` VALUES (363, '台中市', 24);
INSERT INTO `city` VALUES (364, '新竹市', 24);
INSERT INTO `city` VALUES (365, '基隆市', 24);
INSERT INTO `city` VALUES (366, '台南市', 24);
INSERT INTO `city` VALUES (367, '嘉义市　', 24);
INSERT INTO `city` VALUES (368, '齐齐哈尔市', 25);
INSERT INTO `city` VALUES (369, '哈尔滨市', 25);
INSERT INTO `city` VALUES (370, '大庆市', 25);
INSERT INTO `city` VALUES (371, '佳木斯市', 25);
INSERT INTO `city` VALUES (372, '双鸭山市', 25);
INSERT INTO `city` VALUES (373, '牡丹江市', 25);
INSERT INTO `city` VALUES (374, '鸡西市', 25);
INSERT INTO `city` VALUES (375, '黑河市', 25);
INSERT INTO `city` VALUES (376, '绥化市', 25);
INSERT INTO `city` VALUES (377, '鹤岗市', 25);
INSERT INTO `city` VALUES (378, '伊春市', 25);
INSERT INTO `city` VALUES (379, '大兴安岭地区', 25);
INSERT INTO `city` VALUES (380, '七台河市　', 25);
INSERT INTO `city` VALUES (381, '赤峰市', 26);
INSERT INTO `city` VALUES (382, '包头市', 26);
INSERT INTO `city` VALUES (383, '通辽市', 26);
INSERT INTO `city` VALUES (384, '呼和浩特市', 26);
INSERT INTO `city` VALUES (385, '乌海市', 26);
INSERT INTO `city` VALUES (386, '鄂尔多斯市', 26);
INSERT INTO `city` VALUES (387, '呼伦贝尔市', 26);
INSERT INTO `city` VALUES (388, '兴安盟', 26);
INSERT INTO `city` VALUES (389, '巴彦淖尔盟', 26);
INSERT INTO `city` VALUES (390, '乌兰察布盟', 26);
INSERT INTO `city` VALUES (391, '锡林郭勒盟', 26);
INSERT INTO `city` VALUES (392, '阿拉善盟　', 26);
INSERT INTO `city` VALUES (393, '澳门特别行政区', 27);
INSERT INTO `city` VALUES (394, '贵阳市', 28);
INSERT INTO `city` VALUES (395, '黔东南州', 28);
INSERT INTO `city` VALUES (396, '黔南州', 28);
INSERT INTO `city` VALUES (397, '遵义市', 28);
INSERT INTO `city` VALUES (398, '黔西南州', 28);
INSERT INTO `city` VALUES (399, '毕节地区', 28);
INSERT INTO `city` VALUES (400, '铜仁地区', 28);
INSERT INTO `city` VALUES (401, '安顺市', 28);
INSERT INTO `city` VALUES (402, '六盘水市　', NULL);
INSERT INTO `city` VALUES (403, '兰州市', 29);
INSERT INTO `city` VALUES (404, '天水市', 29);
INSERT INTO `city` VALUES (405, '庆阳市', 29);
INSERT INTO `city` VALUES (406, '武威市', 29);
INSERT INTO `city` VALUES (407, '酒泉市', 29);
INSERT INTO `city` VALUES (408, '张掖市', 29);
INSERT INTO `city` VALUES (409, '陇南地区', 29);
INSERT INTO `city` VALUES (410, '白银市', 29);
INSERT INTO `city` VALUES (411, '定西地区', 29);
INSERT INTO `city` VALUES (412, '平凉市', 29);
INSERT INTO `city` VALUES (413, '嘉峪关市', 29);
INSERT INTO `city` VALUES (414, '临夏回族自治州', 29);
INSERT INTO `city` VALUES (415, '金昌市', 29);
INSERT INTO `city` VALUES (416, '甘南州　', 29);
INSERT INTO `city` VALUES (417, '西宁市', 30);
INSERT INTO `city` VALUES (418, '海西州', 30);
INSERT INTO `city` VALUES (419, '海东地区', 30);
INSERT INTO `city` VALUES (420, '海北州', 30);
INSERT INTO `city` VALUES (421, '果洛州', 30);
INSERT INTO `city` VALUES (422, '玉树州', 30);
INSERT INTO `city` VALUES (423, '黄南藏族自治州　', 30);
INSERT INTO `city` VALUES (424, '乌鲁木齐市', 31);
INSERT INTO `city` VALUES (425, '伊犁州', 31);
INSERT INTO `city` VALUES (426, '昌吉州', 31);
INSERT INTO `city` VALUES (427, '石河子市', 31);
INSERT INTO `city` VALUES (428, '哈密地区', 31);
INSERT INTO `city` VALUES (429, '阿克苏地区', 31);
INSERT INTO `city` VALUES (430, '巴音郭楞州', 31);
INSERT INTO `city` VALUES (431, '喀什地区', 31);
INSERT INTO `city` VALUES (432, '塔城地区', 31);
INSERT INTO `city` VALUES (433, '克拉玛依市', 31);
INSERT INTO `city` VALUES (434, '和田地区', 31);
INSERT INTO `city` VALUES (435, '阿勒泰州', 31);
INSERT INTO `city` VALUES (436, '吐鲁番地区', 31);
INSERT INTO `city` VALUES (437, '阿拉尔市', 31);
INSERT INTO `city` VALUES (438, '博尔塔拉州', 31);
INSERT INTO `city` VALUES (439, '五家渠市', 31);
INSERT INTO `city` VALUES (440, '克孜勒苏州', 31);
INSERT INTO `city` VALUES (441, '图木舒克市　', 31);
INSERT INTO `city` VALUES (442, '拉萨市', 32);
INSERT INTO `city` VALUES (443, '山南地区', 32);
INSERT INTO `city` VALUES (444, '林芝地区', 32);
INSERT INTO `city` VALUES (445, '日喀则地区', 32);
INSERT INTO `city` VALUES (446, '阿里地区', 32);
INSERT INTO `city` VALUES (447, '昌都地区', 32);
INSERT INTO `city` VALUES (448, '那曲地区　', 32);
INSERT INTO `city` VALUES (449, '吉林市', 33);
INSERT INTO `city` VALUES (450, '长春市', 33);
INSERT INTO `city` VALUES (451, '白山市', 33);
INSERT INTO `city` VALUES (452, '白城市', 33);
INSERT INTO `city` VALUES (453, '延边州', 33);
INSERT INTO `city` VALUES (454, '松原市', 33);
INSERT INTO `city` VALUES (455, '辽源市', 33);
INSERT INTO `city` VALUES (456, '通化市', 33);
INSERT INTO `city` VALUES (457, '四平市　', 33);
INSERT INTO `city` VALUES (458, '银川市', 34);
INSERT INTO `city` VALUES (459, '吴忠市', 34);
INSERT INTO `city` VALUES (460, '中卫市', 34);
INSERT INTO `city` VALUES (461, '石嘴山市', 34);
INSERT INTO `city` VALUES (462, '固原市', 34);

SET FOREIGN_KEY_CHECKS = 1;
